export const GET_PRODUCTS = 'GET_PRODUCTS'

export const GET_SINGLE_PRODUCT = 'GET_SINGLE_PRODUCT'

export const CREATE_PRODUCT = 'CREATE_PRODUCT'

export const UPDATE_PRODUCT = 'UPDATE_PRODUCT'

export const DELETE_PRODUCT = 'DELETE_PRODUCT'

export const START_LOADING = 'START_LOADING'

export const END_LOADING = 'END_LOADING'

export const AUTH = 'AUTH'

export const LOGOUT = 'LOGOUT'

export const GET_USER_INFO = 'GET_USER_INFO'

export const GET_PAYMENT = 'GET_PAYMENT'

export const GET_CATEGORIES = 'GET_CATEGORIES'

export const CREATE_CATEGORY = 'CREATE_CATEGORY'

export const DELETE_CATEGORY = 'DELETE_CATEGORY'

export const UPDATE_CATEGORY = 'UPDATE_CATEGORY'

export const GET_SINGLE_CATEGORY = 'GET_SINGLE_CATEGORY'